use std::net::SocketAddr;
use std::time::{SystemTime, UNIX_EPOCH};

use aes_gcm::aead::{Aead, KeyInit, Payload};
use aes_gcm::{Aes128Gcm, Key, Nonce};
use anyhow::Result;
use hkdf::Hkdf;
use sha2::Sha256;
use tokio::io::AsyncWriteExt;
use tokio::net::TcpStream;
use tracing::debug;
use x25519_dalek::{EphemeralSecret, PublicKey};

use proxy_common::{BoxedStream, ProxyError};
use proxy_tls::ClientHelloBuilder;

use super::{REALITY_HKDF_INFO, REALITY_TOKEN_VERSION, SESSION_ID_OFFSET_IN_HANDSHAKE_BODY};

/// REALITY client configuration read from the outbound config.
pub struct RealityClientConfig {
    /// The REALITY server's address.
    pub server: SocketAddr,

    /// The server's long-term X25519 public key generated by the server operator.
    pub server_public_key: [u8; 32],

    /// The short ID assigned to this client. The server must allow it.
    pub short_id: Vec<u8>,

    /// The cover-domain SNI to place in the ClientHello.
    pub sni: String,

    /// Which browser fingerprint profile to use. Phase 2 supports Chrome.
    pub fingerprint: String,
}

/// REALITY client: connects to a REALITY server and returns an authenticated stream.
pub struct RealityClient {
    config: RealityClientConfig,
}

impl RealityClient {
    pub fn new(config: RealityClientConfig) -> Self {
        Self { config }
    }

    /// Connect to the REALITY server and perform the REALITY handshake.
    ///
    /// On success, returns a stream that already sent the authenticated
    /// ClientHello. The VLESS layer can then write its payload on the same TCP
    /// stream in the current Phase 2 direct mode.
    pub async fn dial(&self) -> Result<BoxedStream, ProxyError> {
        let mut tcp = TcpStream::connect(self.config.server).await?;
        tcp.set_nodelay(true)?;

        debug!(server = %self.config.server, sni = %self.config.sni, "REALITY dial");

        let (client_pub_bytes, shared_secret) =
            make_client_key_share(self.config.server_public_key);
        let (random, auth_key) = derive_auth_key(shared_secret.as_bytes())?;
        let zero_session_id = [0u8; 32];

        // Build once with a zero session_id. Those zero bytes become the AAD.
        // Do not rebuild later: rebuilding would choose different GREASE values.
        let hello_bytes = {
            // `ThreadRng` is not Send, so keep it inside this small scope.
            // Nothing from this block may live across the later `write_all().await`.
            let mut rng = rand::thread_rng();
            let builder = ClientHelloBuilder::chrome_131();
            builder.build(
                &self.config.sni,
                &random,
                &zero_session_id,
                Some(&client_pub_bytes),
                &mut rng,
            )
        };

        let aad = &hello_bytes[5..]; // skip the TLS record header
        let encrypted_token =
            encrypt_reality_token(&self.config.short_id, &random, &auth_key, aad)?;

        // Patch the ciphertext directly into the session_id slot.
        let mut final_hello = hello_bytes;
        // The constant points at the first session_id byte inside the
        // handshake body. Add only the 5-byte TLS record header here.
        let sid_start = 5 + SESSION_ID_OFFSET_IN_HANDSHAKE_BODY;
        final_hello[sid_start..sid_start + 32].copy_from_slice(&encrypted_token);

        tcp.write_all(&final_hello).await?;
        debug!(server = %self.config.server, "REALITY ClientHello sent");

        Ok(Box::new(tcp))
    }
}

fn make_client_key_share(server_public_key: [u8; 32]) -> ([u8; 32], x25519_dalek::SharedSecret) {
    // One ephemeral key pair is used both for ECDH and for the ClientHello
    // key_share extension, so the server can derive the same secret.
    let client_secret = EphemeralSecret::random_from_rng(rand::thread_rng());
    let client_public = PublicKey::from(&client_secret);
    let client_pub_bytes = *client_public.as_bytes();
    let server_pub_key = PublicKey::from(server_public_key);
    let shared_secret = client_secret.diffie_hellman(&server_pub_key);

    (client_pub_bytes, shared_secret)
}

fn derive_auth_key(shared_secret: &[u8; 32]) -> Result<([u8; 32], [u8; 32]), ProxyError> {
    // REALITY reuses the TLS random field:
    // random[0..20] is the HKDF salt, random[20..32] is the AES-GCM nonce.
    let mut random = [0u8; 32];
    rand::RngCore::fill_bytes(&mut rand::thread_rng(), &mut random);

    let hk = Hkdf::<Sha256>::new(Some(&random[..20]), shared_secret);
    let mut auth_key = [0u8; 32];
    hk.expand(REALITY_HKDF_INFO, &mut auth_key)
        .map_err(|_| ProxyError::Protocol("HKDF expand failed".into()))?;

    Ok((random, auth_key))
}

fn encrypt_reality_token(
    short_id: &[u8],
    random: &[u8; 32],
    auth_key: &[u8; 32],
    aad: &[u8],
) -> Result<[u8; 32], ProxyError> {
    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() as u32;

    let mut plaintext = [0u8; 16];
    plaintext[0] = REALITY_TOKEN_VERSION;
    plaintext[2..6].copy_from_slice(&ts.to_be_bytes());

    // The short ID field is fixed at 8 bytes. Shorter IDs are zero-padded.
    let sid_len = short_id.len().min(8);
    plaintext[6..6 + sid_len].copy_from_slice(&short_id[..sid_len]);

    let cipher = Aes128Gcm::new(Key::<Aes128Gcm>::from_slice(&auth_key[..16]));
    let nonce = Nonce::from_slice(&random[20..32]);
    let output = cipher
        .encrypt(
            nonce,
            Payload {
                msg: &plaintext,
                aad,
            },
        )
        .map_err(|_| ProxyError::Protocol("REALITY token encryption failed".into()))?;

    output
        .try_into()
        .map_err(|_| ProxyError::Protocol("REALITY token encryption length mismatch".into()))
}
