#!/usr/bin/env python3
"""report.py — render latency JSON results as Markdown or HTML.

Usage:
    python3 report.py [--format md|html] [--dir REPORTS_DIR]

Reads the most recent JSON file per variant from REPORTS_DIR and produces
a comparison table sorted by p99 latency.
"""
import argparse
import glob
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path


def find_latest(reports_dir: str) -> list[dict]:
    """Return the most recent result per variant."""
    files = glob.glob(os.path.join(reports_dir, "*.json"))
    by_variant: dict[str, tuple[str, dict]] = {}
    for path in files:
        try:
            with open(path) as f:
                data = json.load(f)
        except (json.JSONDecodeError, OSError):
            continue
        variant = data.get("variant", os.path.basename(path))
        ts = data.get("timestamp", "")
        prev_ts = by_variant.get(variant, ("", {}))[0]
        if ts > prev_ts:
            by_variant[variant] = (ts, data)
    return [v for _, v in sorted(by_variant.values(), key=lambda x: x[0])]


def ms(secs) -> str:
    """Format seconds as milliseconds with 2 decimal places."""
    try:
        return f"{float(secs) * 1000:.2f}"
    except (TypeError, ValueError):
        return "—"


def render_markdown(results: list[dict]) -> str:
    if not results:
        return "_No results found._\n"

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# Latency Comparison — {now}",
        "",
        "All times in **milliseconds**. Lower is better.",
        "",
        "| Variant | p50 | p90 | p95 | p99 | req/s | errors |",
        "|---------|-----|-----|-----|-----|-------|--------|",
    ]
    for r in results:
        row = "| {variant} | {p50} | {p90} | {p95} | {p99} | {rps} | {err} |".format(
            variant=r.get("variant", "?"),
            p50=ms(r.get("p50_s")),
            p90=ms(r.get("p90_s")),
            p95=ms(r.get("p95_s")),
            p99=ms(r.get("p99_s")),
            rps=f"{float(r.get('requests_per_sec', 0)):.0f}",
            err=r.get("errors", 0),
        )
        lines.append(row)

    lines += [
        "",
        "## Raw",
        "",
        "```json",
        json.dumps(results, indent=2),
        "```",
        "",
        "> Generated by `labs/realistic/latency/scripts/report.py`",
        "> Baselines are machine-specific — do not treat committed samples as universal truth.",
    ]
    return "\n".join(lines) + "\n"


def render_html(results: list[dict]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    rows = ""
    for r in results:
        rows += (
            f"<tr><td>{r.get('variant','?')}</td>"
            f"<td>{ms(r.get('p50_s'))}</td>"
            f"<td>{ms(r.get('p90_s'))}</td>"
            f"<td>{ms(r.get('p95_s'))}</td>"
            f"<td>{ms(r.get('p99_s'))}</td>"
            f"<td>{float(r.get('requests_per_sec',0)):.0f}</td>"
            f"<td>{r.get('errors',0)}</td></tr>\n"
        )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Latency Comparison — {now}</title>
<style>
body {{ font-family: monospace; max-width: 900px; margin: 2em auto; }}
table {{ border-collapse: collapse; width: 100%; }}
th, td {{ border: 1px solid #ccc; padding: 6px 12px; text-align: right; }}
th {{ background: #f4f4f4; text-align: center; }}
td:first-child {{ text-align: left; }}
</style>
</head>
<body>
<h1>Latency Comparison</h1>
<p>{now} — all times in <strong>milliseconds</strong></p>
<table>
<tr><th>Variant</th><th>p50</th><th>p90</th><th>p95</th><th>p99</th><th>req/s</th><th>errors</th></tr>
{rows}</table>
<p><small>
  Generated by <code>labs/realistic/latency/scripts/report.py</code><br>
  Baselines are machine-specific — do not treat committed samples as universal truth.
</small></p>
</body>
</html>
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Render latency JSON results")
    parser.add_argument("--format", choices=["md", "html"], default="md")
    parser.add_argument(
        "--dir",
        default=os.path.join(os.path.dirname(__file__), "..", "reports"),
        help="Directory containing result JSON files",
    )
    parser.add_argument("--out", help="Output file (default: stdout)")
    args = parser.parse_args()

    reports_dir = os.path.realpath(args.dir)
    if not os.path.isdir(reports_dir):
        print(f"ERROR: reports directory not found: {reports_dir}", file=sys.stderr)
        sys.exit(1)

    results = find_latest(reports_dir)
    if not results:
        print(f"No JSON result files found in {reports_dir}", file=sys.stderr)

    output = render_markdown(results) if args.format == "md" else render_html(results)

    if args.out:
        Path(args.out).write_text(output)
        print(f"Wrote {args.out}")
    else:
        print(output, end="")


if __name__ == "__main__":
    main()
