#!/usr/bin/env python3
"""report.py — render latency JSON results as Markdown or HTML.

Usage:
    python3 report.py [--format md|html] [--dir REPORTS_DIR]

Reads the most recent JSON file per variant from REPORTS_DIR and produces
a comparison table sorted by p99 latency.
"""
import argparse
import glob
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path


def find_latest(reports_dir: str) -> list[dict]:
    """Return the most recent result per variant."""
    files = glob.glob(os.path.join(reports_dir, "*.json"))
    by_variant: dict[str, tuple[str, dict]] = {}
    for path in files:
        try:
            with open(path) as f:
                data = json.load(f)
        except (json.JSONDecodeError, OSError):
            continue
        variant = data.get("variant", os.path.basename(path))
        ts = data.get("timestamp", "")
        prev_ts = by_variant.get(variant, ("", {}))[0]
        if ts > prev_ts:
            by_variant[variant] = (ts, data)
    return [v for _, v in sorted(by_variant.values(), key=lambda x: x[0])]


def ms(secs) -> str:
    """Format seconds as milliseconds with 2 decimal places."""
    try:
        return f"{float(secs) * 1000:.2f}"
    except (TypeError, ValueError):
        return "—"


def int_field(result: dict, key: str) -> int:
    try:
        return int(result.get(key, 0) or 0)
    except (TypeError, ValueError):
        return 0


def result_failed(result: dict) -> bool:
    return (
        bool(result.get("benchmark_failed", False))
        or int_field(result, "errors") > 0
        or int_field(result, "non_200_responses") > 0
        or int_field(result, "timeout_errors") > 0
        or int_field(result, "eof_errors") > 0
        or int_field(result, "reset_errors") > 0
        or int_field(result, "connection_refused_errors") > 0
        or int_field(result, "other_errors") > 0
    )


def direct_failures(results: list[dict]) -> list[dict]:
    return [
        r for r in results
        if isinstance(r.get("variant"), str)
        and r["variant"].startswith("direct")
        and result_failed(r)
    ]


def render_markdown(results: list[dict]) -> str:
    if not results:
        return "_No results found._\n"

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# Latency Comparison — {now}",
        "",
        "All times in **milliseconds**. Lower is better.",
        "",
        "| Variant | payload | keepalive | warmup | p50 | p90 | p95 | p99 | req/s | errors | non-200 | status |",
        "|---------|---------|-----------|--------|-----|-----|-----|-----|-------|--------|---------|--------|",
    ]
    direct_failed = direct_failures(results)
    if direct_failed:
        lines += [
            "> **RUN INVALID:** direct baseline has request failures. Treat Fast/Xray/sing-box comparisons as diagnostic only until the upstream/load environment is clean.",
            "",
        ]
    for r in results:
        failed = result_failed(r)
        row = "| {variant} | {payload} | {keepalive} | {warmup} | {p50} | {p90} | {p95} | {p99} | {rps} | {err} | {non200} | {status} |".format(
            variant=r.get("variant", "?"),
            payload=r.get("payload", "—"),
            keepalive="on" if r.get("keepalive", True) else "off",
            warmup=r.get("warmup_s", 0),
            p50=ms(r.get("p50_s")),
            p90=ms(r.get("p90_s")),
            p95=ms(r.get("p95_s")),
            p99=ms(r.get("p99_s")),
            rps=f"{float(r.get('requests_per_sec', 0)):.0f}",
            err=r.get("errors", 0),
            non200=r.get("non_200_responses", 0),
            status="FAIL" if failed else "ok",
        )
        lines.append(row)

    gate_lines = render_fast_gate(results)
    if gate_lines:
        lines += ["", "## Fast Profile Gate", "", *gate_lines]

    lines += [
        "",
        "## Raw",
        "",
        "```json",
        json.dumps(results, indent=2),
        "```",
        "",
        "> Generated by `labs/realistic/latency/scripts/report.py`",
        "> Baselines are machine-specific — do not treat committed samples as universal truth.",
    ]
    return "\n".join(lines) + "\n"


def render_fast_gate(results: list[dict]) -> list[str]:
    by_variant = {r.get("variant"): r for r in results}
    direct_failed = direct_failures(results)
    if direct_failed:
        lines = [
            f"- RUN INVALID: {len(direct_failed)} direct baseline variant(s) failed. Fix the benchmark environment before using this as a release gate."
        ]
        for r in direct_failed:
            lines.append(
                f"- Direct `{r.get('variant')}` failed with errors={int_field(r, 'errors')}, non_200={int_field(r, 'non_200_responses')}, timeouts={int_field(r, 'timeout_errors')}, eof={int_field(r, 'eof_errors')}, reset={int_field(r, 'reset_errors')}."
            )
        return lines
    pairs = []
    for variant, result in by_variant.items():
        if not isinstance(variant, str):
            continue
        if variant.startswith("xray-bw-fast-tcp"):
            pairs.append(("Xray", result, by_variant.get(variant.replace("xray-bw-fast-tcp", "xray-xray-tcp", 1))))
        elif variant.startswith("singbox-bw-fast-tcp"):
            pairs.append((
                "sing-box",
                result,
                by_variant.get(variant.replace("singbox-bw-fast-tcp", "singbox-singbox-tcp", 1)),
            ))
    lines: list[str] = []
    for label, fast, competitor in pairs:
        if not fast or not competitor:
            continue
        checks = []
        for key in ("p50_s", "p95_s", "p99_s"):
            checks.append(float(fast.get(key, 0)) <= float(competitor.get(key, 0)) * 1.05)
        checks.append(
            float(fast.get("requests_per_sec", 0))
            >= float(competitor.get("requests_per_sec", 0)) * 0.95
        )
        checks.append(not result_failed(fast))
        status = "PASS" if all(checks) else "FAIL"
        lines.append(
            f"- {label} `{fast.get('variant')}`: {status} — fast vs matching baseline must be within 5% on p50/p95/p99/req/s with zero errors and zero non-200 responses."
        )
    return lines


def render_html(results: list[dict]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    rows = ""
    for r in results:
        failed = result_failed(r)
        rows += (
            f"<tr><td>{r.get('variant','?')}</td>"
            f"<td>{r.get('payload','—')}</td>"
            f"<td>{'on' if r.get('keepalive', True) else 'off'}</td>"
            f"<td>{r.get('warmup_s', 0)}</td>"
            f"<td>{ms(r.get('p50_s'))}</td>"
            f"<td>{ms(r.get('p90_s'))}</td>"
            f"<td>{ms(r.get('p95_s'))}</td>"
            f"<td>{ms(r.get('p99_s'))}</td>"
            f"<td>{float(r.get('requests_per_sec',0)):.0f}</td>"
            f"<td>{r.get('errors',0)}</td>"
            f"<td>{r.get('non_200_responses',0)}</td>"
            f"<td>{'FAIL' if failed else 'ok'}</td></tr>\n"
        )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Latency Comparison — {now}</title>
<style>
body {{ font-family: monospace; max-width: 900px; margin: 2em auto; }}
table {{ border-collapse: collapse; width: 100%; }}
th, td {{ border: 1px solid #ccc; padding: 6px 12px; text-align: right; }}
th {{ background: #f4f4f4; text-align: center; }}
td:first-child {{ text-align: left; }}
</style>
</head>
<body>
<h1>Latency Comparison</h1>
<p>{now} — all times in <strong>milliseconds</strong></p>
<table>
<tr><th>Variant</th><th>payload</th><th>keepalive</th><th>warmup</th><th>p50</th><th>p90</th><th>p95</th><th>p99</th><th>req/s</th><th>errors</th><th>non-200</th><th>status</th></tr>
{rows}</table>
<p><small>
  Generated by <code>labs/realistic/latency/scripts/report.py</code><br>
  Baselines are machine-specific — do not treat committed samples as universal truth.
</small></p>
</body>
</html>
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Render latency JSON results")
    parser.add_argument("--format", choices=["md", "html"], default="md")
    parser.add_argument(
        "--dir",
        default=os.path.join(os.path.dirname(__file__), "..", "reports"),
        help="Directory containing result JSON files",
    )
    parser.add_argument("--out", help="Output file (default: stdout)")
    args = parser.parse_args()

    reports_dir = os.path.realpath(args.dir)
    if not os.path.isdir(reports_dir):
        print(f"ERROR: reports directory not found: {reports_dir}", file=sys.stderr)
        sys.exit(1)

    results = find_latest(reports_dir)
    if not results:
        print(f"No JSON result files found in {reports_dir}", file=sys.stderr)

    output = render_markdown(results) if args.format == "md" else render_html(results)

    if args.out:
        Path(args.out).write_text(output)
        print(f"Wrote {args.out}")
    else:
        print(output, end="")


if __name__ == "__main__":
    main()
