use std::net::SocketAddr;
use std::time::{SystemTime, UNIX_EPOCH};

use aes_gcm::aead::{Aead, KeyInit, Payload};
use aes_gcm::{Aes256Gcm, Key, Nonce};
use anyhow::Result;
use hkdf::Hkdf;
use p256::ecdh::EphemeralSecret as P256EphemeralSecret;
use p256::elliptic_curve::rand_core::OsRng;
use p256::elliptic_curve::sec1::ToEncodedPoint;
use rand::RngExt;
use sha2::Sha256;
use tokio::io::AsyncWriteExt;
use tracing::debug;
use x25519_dalek::{PublicKey, StaticSecret};

use blackwire_common::{tcp_connect, BoxedStream, ProxyError};
use blackwire_tls::ClientHelloBuilder;

use super::{
    tls13::{complete_tls13_handshake, Tls13Stream},
    REALITY_HKDF_INFO, REALITY_TOKEN_PLAINTEXT_LEN, SESSION_ID_OFFSET_IN_HANDSHAKE_BODY,
};

/// REALITY client configuration read from the outbound config.
pub struct RealityClientConfig {
    /// The REALITY server's address.
    pub server: SocketAddr,

    /// The server's long-term X25519 public key generated by the server operator.
    pub server_public_key: [u8; 32],

    /// The short ID assigned to this client. The server must allow it.
    pub short_id: Vec<u8>,

    /// The cover-domain SNI to place in the ClientHello.
    pub sni: String,

    /// Which browser fingerprint profile to use. Currently supports Chrome.
    pub fingerprint: String,
}

/// REALITY client: connects to a REALITY server and returns an authenticated stream.
pub struct RealityClient {
    config: RealityClientConfig,
}

impl RealityClient {
    /// Create a REALITY client from validated config values.
    pub fn new(config: RealityClientConfig) -> Self {
        Self { config }
    }

    /// Connect to the REALITY server and complete the full TLS 1.3 handshake.
    ///
    /// After sending the REALITY-authenticated ClientHello, we continue
    /// the TLS handshake (derive keys, decrypt server messages, send Finished)
    /// so that `hs.c.isHandshakeComplete` is true on the Xray side.  The
    /// returned stream is ready for application-data I/O.
    pub async fn dial(&self) -> Result<BoxedStream, ProxyError> {
        let mut tcp = tcp_connect(self.config.server).await?;
        tcp.set_nodelay(true)?;

        debug!(server = %self.config.server, sni = %self.config.sni, "REALITY dial");

        // Generate a StaticSecret so we can do two DH operations:
        //   1. ECDH(client_eph, server_static)  → REALITY auth key
        //   2. ECDH(client_eph, server_tls_eph) → TLS 1.3 handshake secret
        // Some cover origins prefer P-256 and trigger a HelloRetryRequest if we
        // offer only x25519, so we also include a secp256r1 key share in the
        // first ClientHello.
        let key_shares = make_client_key_shares(self.config.server_public_key);

        let (random, auth_key) = derive_auth_key(key_shares.auth_shared_secret.as_bytes())?;
        let zero_session_id = [0u8; 32];

        // Build once with a zero session_id. Those zero bytes become the AAD.
        // Do not rebuild later: rebuilding would choose different GREASE values.
        let hello_bytes = {
            // `ThreadRng` is not Send, so keep it inside this small scope.
            // Nothing from this block may live across the later `write_all().await`.
            let mut rng = rand::rng();
            let builder = ClientHelloBuilder::chrome_131();
            builder.build_with_additional_key_share(
                &self.config.sni,
                &random,
                &zero_session_id,
                Some(&key_shares.x25519_public),
                Some(key_shares.secp256r1_public.as_slice()),
                &mut rng,
            )
        };

        let aad = &hello_bytes[5..]; // skip the TLS record header
        let encrypted_token =
            encrypt_reality_token(&self.config.short_id, &random, &auth_key, aad)?;

        // Patch the ciphertext directly into the session_id slot.
        let mut final_hello = hello_bytes;
        // The constant points at the first session_id byte inside the
        // handshake body. Add only the 5-byte TLS record header here.
        let sid_start = 5 + SESSION_ID_OFFSET_IN_HANDSHAKE_BODY;
        final_hello[sid_start..sid_start + 32].copy_from_slice(&encrypted_token);

        tcp.write_all(&final_hello).await?;
        debug!(server = %self.config.server, "REALITY ClientHello sent");

        // ── Complete TLS 1.3 handshake ───────────────────────────────────────
        // final_hello[5..] is the ClientHello handshake body (without the 5-byte
        // TLS record header). It forms the start of the TLS transcript.
        let client_hello_hs_body = &final_hello[5..];
        let app_keys = complete_tls13_handshake(
            &mut tcp,
            client_hello_hs_body,
            &key_shares.x25519_secret,
            Some(&key_shares.secp256r1_secret),
            &auth_key,
        )
        .await?;

        debug!(server = %self.config.server, "REALITY TLS 1.3 handshake complete");
        Ok(Box::new(Tls13Stream::new(Box::new(tcp), app_keys)))
    }
}

struct ClientKeyShares {
    x25519_public: [u8; 32],
    x25519_secret: StaticSecret,
    auth_shared_secret: x25519_dalek::SharedSecret,
    secp256r1_public: Vec<u8>,
    secp256r1_secret: P256EphemeralSecret,
}

/// Generate the REALITY-auth x25519 key material plus a TLS P-256 key share
/// for origins that select `secp256r1`.
fn make_client_key_shares(server_public_key: [u8; 32]) -> ClientKeyShares {
    let client_secret = StaticSecret::random();
    let client_public = PublicKey::from(&client_secret);
    let client_pub_bytes = *client_public.as_bytes();
    let server_pub_key = PublicKey::from(server_public_key);
    // REALITY auth DH: ECDH(client_eph, server_static) — does NOT consume the secret.
    let shared_secret = client_secret.diffie_hellman(&server_pub_key);
    let secp256r1_secret = P256EphemeralSecret::random(&mut OsRng);
    let secp256r1_public = secp256r1_secret
        .public_key()
        .to_encoded_point(false)
        .as_bytes()
        .to_vec();

    ClientKeyShares {
        x25519_public: client_pub_bytes,
        x25519_secret: client_secret,
        auth_shared_secret: shared_secret,
        secp256r1_public,
        secp256r1_secret,
    }
}

fn derive_auth_key(shared_secret: &[u8; 32]) -> Result<([u8; 32], [u8; 32]), ProxyError> {
    // REALITY reuses the TLS random field:
    // random[0..20] is the HKDF salt, random[20..32] is the AES-GCM nonce.
    let mut random = [0u8; 32];
    rand::rng().fill(&mut random[..]);

    let hk = Hkdf::<Sha256>::new(Some(&random[..20]), shared_secret);
    let mut auth_key = [0u8; 32];
    hk.expand(REALITY_HKDF_INFO, &mut auth_key)
        .map_err(|_| ProxyError::Protocol("HKDF expand failed".into()))?;

    Ok((random, auth_key))
}

fn encrypt_reality_token(
    short_id: &[u8],
    random: &[u8; 32],
    auth_key: &[u8; 32],
    aad: &[u8],
) -> Result<[u8; 32], ProxyError> {
    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() as u32;

    // Layout matches Xray-core / sing-box (xtls/reality): 4-byte client version,
    // 4-byte big-endian Unix timestamp, 8-byte short ID (zero-padded).
    let mut plaintext = [0u8; REALITY_TOKEN_PLAINTEXT_LEN];
    plaintext[4..8].copy_from_slice(&ts.to_be_bytes());
    let sid_len = short_id.len().min(8);
    plaintext[8..8 + sid_len].copy_from_slice(&short_id[..sid_len]);

    let cipher = Aes256Gcm::new(Key::<Aes256Gcm>::from_slice(auth_key));
    let nonce = Nonce::from_slice(&random[20..32]);
    let output = cipher
        .encrypt(
            nonce,
            Payload {
                msg: &plaintext,
                aad,
            },
        )
        .map_err(|_| ProxyError::Protocol("REALITY token encryption failed".into()))?;

    output
        .try_into()
        .map_err(|_| ProxyError::Protocol("REALITY token encryption length mismatch".into()))
}
