//! blackwire-api — gRPC management and statistics API (Phase 6 stub).
//!
//! # What this crate will do
//!
//! In Phase 6, this crate exposes a gRPC server that implements the same
//! protocol as v2ray-core's `StatsService` and `HandlerService`. This lets
//! existing v2ray management tools (v2rayN, v2rayA, etc.) talk to our server
//! without modification.
//!
//! The gRPC service lets you:
//!   - Query per-user bandwidth statistics (bytes sent/received).
//!   - Add or remove users at runtime without restarting.
//!   - Query the proxy version and uptime.
//!
//! # Wire protocol
//!
//! The gRPC service uses `tonic` (Rust gRPC library) with protobuf schemas
//! that match v2ray-core's `.proto` files. The compiled protobuf stubs
//! will live in `src/gen/` (generated by `prost` at build time via
//! `build.rs`).
//!
//! # Phase 1 status
//!
//! This crate is currently a stub. It will be implemented in Phase 6.
//! It exists now so the workspace compiles and the dependency graph is
//! established without code changes later.

// Phase 6 will add:
//   mod gen;                // prost-generated gRPC stubs
//   pub mod stats_service;  // StatsService implementation
//   pub mod handler_service; // HandlerService implementation
//   pub mod server;         // gRPC server start/stop
